apiVersion: v1
kind: Pod
metadata:
  name: todoapp
  namespace: todoapp
  labels:
    app: todoapp
spec:
  containers:
    - name: todoapp
      image: gasterlab/todoapp:3.0.0
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          port: 8080
          path: /api/health/
        initialDelaySeconds: 60
        periodSeconds: 5
      readinessProbe:
        httpGet:
          port: 8080
          path: /api/ready/
        initialDelaySeconds: 5
        periodSeconds: 5
